# Generated by Django 5.1 on 2024-08-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_calculationresult_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
