# Generated by Django 5.1 on 2024-08-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_customprompt_gptprompthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('prompt', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomPrompt',
        ),
        migrations.DeleteModel(
            name='GPTPromptHistory',
        ),
    ]
