# Generated by Django 5.1 on 2024-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_calculationresult_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='gptresult',
            name='file_path',
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gptresult',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
