# Generated by Django 5.1 on 2024-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_remove_calculationresult_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptresult',
            name='prefix',
            field=models.CharField(default='TIPA', max_length=10),
            preserve_default=False,
        ),
    ]
