# Generated by Django 5.1 on 2024-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_gptresult_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gptresult',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
